version: '3'

services:
  ## config servers with 3 replica set
  configSever_1:
    container_name: configSever_1
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - configSever_1:/data/db

  configSever_2:
    container_name: configSever_2
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - configSever_2:/data/db

  configSever_3:
    container_name: configSever_3
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - configSever_3:/data/db

  ## mongos server
  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/192.168.1.81:40001,192.168.1.81:40002,192.168.1.81:40003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017

  ## shard 1 with 3 replica set
  shard_1_sever_1:
    container_name: shard_1_sever_1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shard_1_sever_1:/data/db

  shard_1_sever_2:
    container_name: shard_1_sever_2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - shard_1_sever_2:/data/db

  shard_1_sever_3:
    container_name: shard_1_sever_3
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - shard_1_sever_3:/data/db

  ## shard 2 with 3 replica set
  shard_2_sever_1:
    container_name: shard_2_sever_1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - shard_2_sever_1:/data/db

  shard_2_sever_2:
    container_name: shard_2_sever_2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50005:27017
    volumes:
      - shard_2_sever_2:/data/db

  shard_2_sever_3:
    container_name: shard_2_sever_3
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50006:27017
    volumes:
      - shard_2_sever_3:/data/db

volumes:
  configSever_1: {}
  configSever_2: {}
  configSever_3: {}

  shard_1_sever_1: {}
  shard_1_sever_2: {}
  shard_1_sever_3: {}

  shard_2_sever_1: {}
  shard_2_sever_2: {}
  shard_2_sever_3: {}
